/**
 * @license
 * Copyright 2025 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 */

import type {
  MCPServerConfig,
  BugCommandSettings,
  TelemetrySettings,
  AuthType,
  ChatCompressionSettings,
} from '@qwen-code/qwen-code-core';
import type { CustomTheme } from '../ui/themes/theme.js';

export interface SettingDefinition {
  type: 'boolean' | 'string' | 'number' | 'array' | 'object';
  label: string;
  category: string;
  requiresRestart: boolean;
  default: boolean | string | number | string[] | object | undefined;
  description?: string;
  parentKey?: string;
  childKey?: string;
  key?: string;
  properties?: SettingsSchema;
  showInDialog?: boolean;
}

export interface SettingsSchema {
  [key: string]: SettingDefinition;
}

export type MemoryImportFormat = 'tree' | 'flat';
export type DnsResolutionOrder = 'ipv4first' | 'verbatim';

/**
 * The canonical schema for all settings.
 * The structure of this object defines the structure of the `Settings` type.
 * `as const` is crucial for TypeScript to infer the most specific types possible.
 */
export const SETTINGS_SCHEMA = {
  // Maintained for compatibility/criticality
  mcpServers: {
    type: 'object',
    label: 'MCP 服务器',
    category: '高级',
    requiresRestart: true,
    default: {} as Record<string, MCPServerConfig>,
    description: 'MCP 服务器配置。',
    showInDialog: false,
  },

  general: {
    type: 'object',
    label: '通用',
    category: '通用',
    requiresRestart: false,
    default: {},
    description: '通用应用程序设置。',
    showInDialog: false,
    properties: {
      preferredEditor: {
        type: 'string',
        label: '首选编辑器',
        category: '通用',
        requiresRestart: false,
        default: undefined as string | undefined,
        description: '打开文件的首选编辑器。',
        showInDialog: false,
      },
      vimMode: {
        type: 'boolean',
        label: 'Vim 模式',
        category: '通用',
        requiresRestart: false,
        default: false,
        description: '启用 Vim 键绑定',
        showInDialog: true,
      },
      disableAutoUpdate: {
        type: 'boolean',
        label: '禁用自动更新',
        category: '通用',
        requiresRestart: false,
        default: false,
        description: '禁用自动更新',
        showInDialog: true,
      },
      disableUpdateNag: {
        type: 'boolean',
        label: '禁用更新提示',
        category: '通用',
        requiresRestart: false,
        default: false,
        description: '禁用更新通知提示。',
        showInDialog: false,
      },
      checkpointing: {
        type: 'object',
        label: '检查点',
        category: '通用',
        requiresRestart: true,
        default: {},
        description: '会话检查点设置。',
        showInDialog: false,
        properties: {
          enabled: {
            type: 'boolean',
            label: '启用检查点',
            category: '通用',
            requiresRestart: true,
            default: false,
            description: '启用会话检查点以进行恢复',
            showInDialog: false,
          },
        },
      },
      enablePromptCompletion: {
        type: 'boolean',
        label: '启用提示补全',
        category: '通用',
        requiresRestart: true,
        default: false,
        description: '在输入时启用 AI 驱动的提示补全建议。',
        showInDialog: true,
      },
      debugKeystrokeLogging: {
        type: 'boolean',
        label: '调试按键记录',
        category: '通用',
        requiresRestart: false,
        default: false,
        description: '启用按键调试日志记录到控制台。',
        showInDialog: true,
      },
    },
  },

  ui: {
    type: 'object',
    label: '用户界面',
    category: '用户界面',
    requiresRestart: false,
    default: {},
    description: '用户界面设置。',
    showInDialog: false,
    properties: {
      theme: {
        type: 'string',
        label: '主题',
        category: '用户界面',
        requiresRestart: false,
        default: undefined as string | undefined,
        description: '用户界面的颜色主题。',
        showInDialog: false,
      },
      customThemes: {
        type: 'object',
        label: '自定义主题',
        category: '用户界面',
        requiresRestart: false,
        default: {} as Record<string, CustomTheme>,
        description: '自定义主题定义。',
        showInDialog: false,
      },
      hideWindowTitle: {
        type: 'boolean',
        label: '隐藏窗口标题',
        category: '用户界面',
        requiresRestart: true,
        default: false,
        description: '隐藏窗口标题栏',
        showInDialog: true,
      },
      hideTips: {
        type: 'boolean',
        label: '隐藏提示',
        category: '用户界面',
        requiresRestart: false,
        default: false,
        description: '在用户界面中隐藏有用提示',
        showInDialog: true,
      },
      hideBanner: {
        type: 'boolean',
        label: '隐藏横幅',
        category: '用户界面',
        requiresRestart: false,
        default: false,
        description: '隐藏应用程序横幅',
        showInDialog: true,
      },
      hideFooter: {
        type: 'boolean',
        label: '隐藏页脚',
        category: '用户界面',
        requiresRestart: false,
        default: false,
        description: '在用户界面中隐藏页脚',
        showInDialog: true,
      },
      showMemoryUsage: {
        type: 'boolean',
        label: '显示内存使用情况',
        category: '用户界面',
        requiresRestart: false,
        default: false,
        description: '在用户界面中显示内存使用信息',
        showInDialog: true,
      },
      showLineNumbers: {
        type: 'boolean',
        label: '显示行号',
        category: '用户界面',
        requiresRestart: false,
        default: false,
        description: '在聊天中显示行号。',
        showInDialog: true,
      },
      accessibility: {
        type: 'object',
        label: '无障碍功能',
        category: '用户界面',
        requiresRestart: true,
        default: {},
        description: '无障碍功能设置。',
        showInDialog: false,
        properties: {
          disableLoadingPhrases: {
            type: 'boolean',
            label: '禁用加载短语',
            category: '用户界面',
            requiresRestart: true,
            default: false,
            description: '为无障碍功能禁用加载短语',
            showInDialog: true,
          },
          screenReader: {
            type: 'boolean',
            label: '屏幕阅读器模式',
            category: '用户界面',
            requiresRestart: true,
            default: undefined as boolean | undefined,
            description: '以纯文本形式渲染输出，使屏幕阅读器更易访问',
            showInDialog: true,
          },
        },
      },
    },
  },

  ide: {
    type: 'object',
    label: '集成开发环境',
    category: '集成开发环境',
    requiresRestart: true,
    default: {},
    description: '集成开发环境集成设置。',
    showInDialog: false,
    properties: {
      enabled: {
        type: 'boolean',
        label: '集成开发环境模式',
        category: '集成开发环境',
        requiresRestart: true,
        default: false,
        description: '启用集成开发环境集成功能',
        showInDialog: true,
      },
      hasSeenNudge: {
        type: 'boolean',
        label: '已查看集成开发环境集成提示',
        category: '集成开发环境',
        requiresRestart: false,
        default: false,
        description: '用户是否已查看集成开发环境集成功能提示。',
        showInDialog: false,
      },
    },
  },

  privacy: {
    type: 'object',
    label: '隐私',
    category: '隐私',
    requiresRestart: true,
    default: {},
    description: '隐私相关设置。',
    showInDialog: false,
    properties: {
      usageStatisticsEnabled: {
        type: 'boolean',
        label: '启用使用统计',
        category: '隐私',
        requiresRestart: true,
        default: true,
        description: '启用使用统计信息收集',
        showInDialog: false,
      },
    },
  },

  telemetry: {
    type: 'object',
    label: '遥测',
    category: '高级',
    requiresRestart: true,
    default: undefined as TelemetrySettings | undefined,
    description: '遥测配置。',
    showInDialog: false,
  },

  model: {
    type: 'object',
    label: '模型',
    category: '模型',
    requiresRestart: false,
    default: {},
    description: '生成模型相关设置。',
    showInDialog: false,
    properties: {
      name: {
        type: 'string',
        label: '模型',
        category: '模型',
        requiresRestart: false,
        default: undefined as string | undefined,
        description: '用于对话的 Gemini 模型。',
        showInDialog: false,
      },
      maxSessionTurns: {
        type: 'number',
        label: '最大会话轮次',
        category: '模型',
        requiresRestart: false,
        default: -1,
        description: '会话中保留的最大用户/模型/工具轮次。-1 表示无限制。',
        showInDialog: true,
      },
      summarizeToolOutput: {
        type: 'object',
        label: '汇总工具输出',
        category: '模型',
        requiresRestart: false,
        default: undefined as
          | Record<string, { tokenBudget?: number }>
          | undefined,
        description: '工具输出汇总设置。',
        showInDialog: false,
      },
      chatCompression: {
        type: 'object',
        label: '聊天压缩',
        category: '模型',
        requiresRestart: false,
        default: undefined as ChatCompressionSettings | undefined,
        description: '聊天压缩设置。',
        showInDialog: false,
      },
      skipNextSpeakerCheck: {
        type: 'boolean',
        label: '跳过下一个发言者检查',
        category: '模型',
        requiresRestart: false,
        default: false,
        description: '跳过下一个发言者检查。',
        showInDialog: true,
      },
    },
  },

  context: {
    type: 'object',
    label: '上下文',
    category: '上下文',
    requiresRestart: false,
    default: {},
    description: '管理提供给模型的上下文的设置。',
    showInDialog: false,
    properties: {
      fileName: {
        type: 'object',
        label: '上下文文件名',
        category: '上下文',
        requiresRestart: false,
        default: undefined as string | string[] | undefined,
        description: '上下文文件的名称。',
        showInDialog: false,
      },
      importFormat: {
        type: 'string',
        label: '内存导入格式',
        category: '上下文',
        requiresRestart: false,
        default: undefined as MemoryImportFormat | undefined,
        description: '导入内存时使用的格式。',
        showInDialog: false,
      },
      discoveryMaxDirs: {
        type: 'number',
        label: '内存发现最大目录数',
        category: '上下文',
        requiresRestart: false,
        default: 200,
        description: '搜索内存的最大目录数。',
        showInDialog: true,
      },
      includeDirectories: {
        type: 'array',
        label: '包含目录',
        category: '上下文',
        requiresRestart: false,
        default: [] as string[],
        description: '包含在工作区上下文中的其他目录。缺失的目录将被跳过并显示警告。',
        showInDialog: false,
      },
      loadMemoryFromIncludeDirectories: {
        type: 'boolean',
        label: '从包含目录加载内存',
        category: '上下文',
        requiresRestart: false,
        default: false,
        description: '是否从包含目录加载内存文件。',
        showInDialog: true,
      },
      fileFiltering: {
        type: 'object',
        label: '文件过滤',
        category: '上下文',
        requiresRestart: true,
        default: {},
        description: 'Git 感知文件过滤设置。',
        showInDialog: false,
        properties: {
          respectGitIgnore: {
            type: 'boolean',
            label: '遵循 .gitignore',
            category: '上下文',
            requiresRestart: true,
            default: true,
            description: '搜索时遵循 .gitignore 文件',
            showInDialog: true,
          },
          respectGeminiIgnore: {
            type: 'boolean',
            label: '遵循 .qwenignore',
            category: '上下文',
            requiresRestart: true,
            default: true,
            description: '搜索时遵循 .qwenignore 文件',
            showInDialog: true,
          },
          enableRecursiveFileSearch: {
            type: 'boolean',
            label: '启用递归文件搜索',
            category: '上下文',
            requiresRestart: true,
            default: true,
            description: '启用递归文件搜索功能',
            showInDialog: true,
          },
          disableFuzzySearch: {
            type: 'boolean',
            label: '禁用模糊搜索',
            category: '上下文',
            requiresRestart: true,
            default: false,
            description: '搜索文件时禁用模糊搜索。',
            showInDialog: true,
          },
        },
      },
    },
  },

  tools: {
    type: 'object',
    label: '工具',
    category: '工具',
    requiresRestart: true,
    default: {},
    description: '内置和自定义工具的设置。',
    showInDialog: false,
    properties: {
      sandbox: {
        type: 'object',
        label: '沙箱',
        category: '工具',
        requiresRestart: true,
        default: undefined as boolean | string | undefined,
        description: '沙箱执行环境（可以是布尔值或路径字符串）。',
        showInDialog: false,
      },
      usePty: {
        type: 'boolean',
        label: '使用 node-pty 执行 Shell',
        category: '工具',
        requiresRestart: true,
        default: false,
        description: '使用 node-pty 执行 shell 命令。仍然适用回退到 child_process。',
        showInDialog: true,
      },
      core: {
        type: 'array',
        label: '核心工具',
        category: '工具',
        requiresRestart: true,
        default: undefined as string[] | undefined,
        description: '核心工具定义的路径。',
        showInDialog: false,
      },
      allowed: {
        type: 'array',
        label: '允许的工具',
        category: '高级',
        requiresRestart: true,
        default: undefined as string[] | undefined,
        description: '将绕过确认对话框的工具名称列表。',
        showInDialog: false,
      },
      exclude: {
        type: 'array',
        label: '排除工具',
        category: '工具',
        requiresRestart: true,
        default: undefined as string[] | undefined,
        description: '从发现中排除的工具名称。',
        showInDialog: false,
      },
      discoveryCommand: {
        type: 'string',
        label: '工具发现命令',
        category: '工具',
        requiresRestart: true,
        default: undefined as string | undefined,
        description: '用于工具发现的命令。',
        showInDialog: false,
      },
      callCommand: {
        type: 'string',
        label: '工具调用命令',
        category: '工具',
        requiresRestart: true,
        default: undefined as string | undefined,
        description: '用于工具调用的命令。',
        showInDialog: false,
      },
      useRipgrep: {
        type: 'boolean',
        label: '使用 Ripgrep',
        category: '工具',
        requiresRestart: false,
        default: false,
        description: '使用 ripgrep 进行文件内容搜索而不是回退实现。提供更快的搜索性能。',
        showInDialog: true,
      },
    },
  },

  mcp: {
    type: 'object',
    label: 'MCP',
    category: 'MCP',
    requiresRestart: true,
    default: {},
    description: '模型上下文协议 (MCP) 服务器设置。',
    showInDialog: false,
    properties: {
      serverCommand: {
        type: 'string',
        label: 'MCP 服务器命令',
        category: 'MCP',
        requiresRestart: true,
        default: undefined as string | undefined,
        description: '启动 MCP 服务器的命令。',
        showInDialog: false,
      },
      allowed: {
        type: 'array',
        label: '允许的 MCP 服务器',
        category: 'MCP',
        requiresRestart: true,
        default: undefined as string[] | undefined,
        description: '允许的 MCP 服务器白名单。',
        showInDialog: false,
      },
      excluded: {
        type: 'array',
        label: '排除的 MCP 服务器',
        category: 'MCP',
        requiresRestart: true,
        default: undefined as string[] | undefined,
        description: '排除的 MCP 服务器黑名单。',
        showInDialog: false,
      },
    },
  },

  security: {
    type: 'object',
    label: '安全',
    category: '安全',
    requiresRestart: true,
    default: {},
    description: '安全相关设置。',
    showInDialog: false,
    properties: {
      folderTrust: {
        type: 'object',
        label: '文件夹信任',
        category: '安全',
        requiresRestart: false,
        default: {},
        description: '文件夹信任设置。',
        showInDialog: false,
        properties: {
          featureEnabled: {
            type: 'boolean',
            label: '文件夹信任功能',
            category: '安全',
            requiresRestart: false,
            default: false,
            description: '启用文件夹信任功能以增强安全性。',
            showInDialog: true,
          },
          enabled: {
            type: 'boolean',
            label: '文件夹信任',
            category: '安全',
            requiresRestart: false,
            default: false,
            description: '跟踪文件夹信任是否启用的设置。',
            showInDialog: true,
          },
        },
      },
      auth: {
        type: 'object',
        label: '认证',
        category: '安全',
        requiresRestart: true,
        default: {},
        description: '认证设置。',
        showInDialog: false,
        properties: {
          selectedType: {
            type: 'string',
            label: '选择的认证类型',
            category: '安全',
            requiresRestart: true,
            default: undefined as AuthType | undefined,
            description: '当前选择的认证类型。',
            showInDialog: false,
          },
          useExternal: {
            type: 'boolean',
            label: '使用外部认证',
            category: '安全',
            requiresRestart: true,
            default: undefined as boolean | undefined,
            description: '是否使用外部认证流程。',
            showInDialog: false,
          },
        },
      },
    },
  },

  advanced: {
    type: 'object',
    label: '高级',
    category: '高级',
    requiresRestart: true,
    default: {},
    description: '高级用户设置。',
    showInDialog: false,
    properties: {
      autoConfigureMemory: {
        type: 'boolean',
        label: '自动配置最大旧空间大小',
        category: '高级',
        requiresRestart: true,
        default: false,
        description: '自动配置 Node.js 内存限制',
        showInDialog: false,
      },
      dnsResolutionOrder: {
        type: 'string',
        label: 'DNS 解析顺序',
        category: '高级',
        requiresRestart: true,
        default: undefined as DnsResolutionOrder | undefined,
        description: 'DNS 解析顺序。',
        showInDialog: false,
      },
      excludedEnvVars: {
        type: 'array',
        label: '排除的项目环境变量',
        category: '高级',
        requiresRestart: false,
        default: ['DEBUG', 'DEBUG_MODE'] as string[],
        description: '从项目上下文中排除的环境变量。',
        showInDialog: false,
      },
      bugCommand: {
        type: 'object',
        label: '错误报告命令',
        category: '高级',
        requiresRestart: false,
        default: undefined as BugCommandSettings | undefined,
        description: '错误报告命令的配置。',
        showInDialog: false,
      },
    },
  },

  experimental: {
    type: 'object',
    label: '实验性',
    category: '实验性',
    requiresRestart: true,
    default: {},
    description: '启用实验性功能的设置',
    showInDialog: false,
    properties: {
      extensionManagement: {
        type: 'boolean',
        label: '扩展管理',
        category: '实验性',
        requiresRestart: true,
        default: false,
        description: '启用扩展管理功能。',
        showInDialog: false,
      },
      visionModelPreview: {
        type: 'boolean',
        label: '视觉模型预览',
        category: '实验性',
        requiresRestart: false,
        default: true,
        description: '启用视觉模型支持和自动切换功能。禁用时，视觉模型如 qwen-vl-max-latest 将被隐藏且不会自动切换。',
        showInDialog: true,
      },
      vlmSwitchMode: {
        type: 'string',
        label: 'VLM 切换模式',
        category: '实验性',
        requiresRestart: false,
        default: undefined as string | undefined,
        description: '在输入中检测到图像时的默认行为。值：once（一次性切换）、session（整个会话切换）、persist（继续使用当前模型）。如果未设置，每次都会提示用户。这是一项临时实验性功能。',
        showInDialog: false,
      },
    },
  },

  extensions: {
    type: 'object',
    label: '扩展',
    category: '扩展',
    requiresRestart: true,
    default: {},
    description: '扩展设置。',
    showInDialog: false,
    properties: {
      disabled: {
        type: 'array',
        label: '禁用的扩展',
        category: '扩展',
        requiresRestart: true,
        default: [] as string[],
        description: '禁用的扩展列表。',
        showInDialog: false,
      },
      workspacesWithMigrationNudge: {
        type: 'array',
        label: '显示迁移提示的工作区',
        category: '扩展',
        requiresRestart: false,
        default: [] as string[],
        description: '已显示迁移提示的工作区列表。',
        showInDialog: false,
      },
    },
  },
  contentGenerator: {
    type: 'object',
    label: '内容生成器',
    category: '通用',
    requiresRestart: false,
    default: undefined as Record<string, unknown> | undefined,
    description: '内容生成器设置。',
    showInDialog: false,
    properties: {
      timeout: {
        type: 'number',
        label: '超时',
        category: '内容生成器',
        requiresRestart: false,
        default: undefined as number | undefined,
        description: '请求超时时间（毫秒）。',
        parentKey: 'contentGenerator',
        childKey: 'timeout',
        showInDialog: true,
      },
      maxRetries: {
        type: 'number',
        label: '最大重试次数',
        category: '内容生成器',
        requiresRestart: false,
        default: undefined as number | undefined,
        description: '失败请求的最大重试次数。',
        parentKey: 'contentGenerator',
        childKey: 'maxRetries',
        showInDialog: true,
      },
      disableCacheControl: {
        type: 'boolean',
        label: '禁用缓存控制',
        category: '内容生成器',
        requiresRestart: false,
        default: false,
        description: '为 DashScope 提供程序禁用缓存控制。',
        parentKey: 'contentGenerator',
        childKey: 'disableCacheControl',
        showInDialog: true,
      },
    },
  },
  enableOpenAILogging: {
    type: 'boolean',
    label: '启用 OpenAI 日志记录',
    category: '通用',
    requiresRestart: false,
    default: false,
    description: '启用 OpenAI 日志记录。',
    showInDialog: true,
  },
  sessionTokenLimit: {
    type: 'number',
    label: '会话令牌限制',
    category: '通用',
    requiresRestart: false,
    default: undefined as number | undefined,
    description: '会话中允许的最大令牌数。',
    showInDialog: false,
  },
  systemPromptMappings: {
    type: 'object',
    label: '系统提示映射',
    category: '通用',
    requiresRestart: false,
    default: undefined as Record<string, string> | undefined,
    description: '系统提示到模型名称的映射。',
    showInDialog: false,
  },
  tavilyApiKey: {
    type: 'string',
    label: 'Tavily API 密钥',
    category: '通用',
    requiresRestart: false,
    default: undefined as string | undefined,
    description: 'Tavily API 的 API 密钥。',
    showInDialog: false,
  },
  skipNextSpeakerCheck: {
    type: 'boolean',
    label: '跳过下一个发言者检查',
    category: '通用',
    requiresRestart: false,
    default: false,
    description: '跳过下一个发言者检查。',
    showInDialog: true,
  },
  skipLoopDetection: {
    type: 'boolean',
    label: '跳过循环检测',
    category: '通用',
    requiresRestart: false,
    default: false,
    description: '禁用所有循环检测检查（流式传输和 LLM）。',
    showInDialog: true,
  },
  approvalMode: {
    type: 'string',
    label: '默认审批模式',
    category: '通用',
    requiresRestart: false,
    default: 'default',
    description: '工具使用的默认审批模式。有效值：plan、default、auto-edit、yolo。',
    showInDialog: true,
  },
  enableWelcomeBack: {
    type: 'boolean',
    label: '启用欢迎回来',
    category: '用户界面',
    requiresRestart: false,
    default: true,
    description: '当返回到有对话历史的项目时显示欢迎回来对话框。',
    showInDialog: true,
  },
} as const;

type InferSettings<T extends SettingsSchema> = {
  -readonly [K in keyof T]?: T[K] extends { properties: SettingsSchema }
    ? InferSettings<T[K]['properties']>
    : T[K]['default'] extends boolean
      ? boolean
      : T[K]['default'];
};

export type Settings = InferSettings<typeof SETTINGS_SCHEMA>;
